/* =========================================================
   Roll of honour — competition winners by year.
   kind: "nation" (flag by cc) or "club" (crest by name/logo).
   For clubs whose display name differs from the crest key,
   set `logo` to the crest key.
   ========================================================= */
const HONOURS = {
  worldcup: {
    name: "FIFA World Cup", kind: "nation", trophy: { img: "assets/trophies/worldcup.jpg" },
    blurb: "Football's biggest prize — every four years since 1930.",
    winners: [
      { year: 2026, w: "Spain", cc: "ES" },
      { year: 2022, w: "Argentina", cc: "AR" },
      { year: 2018, w: "France", cc: "FR" },
      { year: 2014, w: "Germany", cc: "DE" },
      { year: 2010, w: "Spain", cc: "ES" },
      { year: 2006, w: "Italy", cc: "IT" },
      { year: 2002, w: "Brazil", cc: "BR" },
      { year: 1998, w: "France", cc: "FR" },
      { year: 1994, w: "Brazil", cc: "BR" },
      { year: 1990, w: "West Germany", cc: "DE" },
      { year: 1986, w: "Argentina", cc: "AR" },
      { year: 1982, w: "Italy", cc: "IT" },
      { year: 1978, w: "Argentina", cc: "AR" },
      { year: 1974, w: "West Germany", cc: "DE" },
      { year: 1970, w: "Brazil", cc: "BR" },
      { year: 1966, w: "England", cc: "GB-ENG" },
      { year: 1962, w: "Brazil", cc: "BR" },
      { year: 1958, w: "Brazil", cc: "BR" },
      { year: 1954, w: "West Germany", cc: "DE" },
      { year: 1950, w: "Uruguay", cc: "UY" },
      { year: 1938, w: "Italy", cc: "IT" },
      { year: 1934, w: "Italy", cc: "IT" },
      { year: 1930, w: "Uruguay", cc: "UY" }
    ]
  },
  ucl: {
    name: "UEFA Champions League", kind: "club", trophy: { img: "assets/trophies/ucl.svg" },
    blurb: "The biggest club competition in the world (the old European Cup).",
    winners: [
      { year: 2025, w: "PSG" },
      { year: 2024, w: "Real Madrid" },
      { year: 2023, w: "Manchester City" },
      { year: 2022, w: "Real Madrid" },
      { year: 2021, w: "Chelsea" },
      { year: 2020, w: "Bayern Munich" },
      { year: 2019, w: "Liverpool" },
      { year: 2018, w: "Real Madrid" },
      { year: 2017, w: "Real Madrid" },
      { year: 2016, w: "Real Madrid" },
      { year: 2015, w: "Barcelona" },
      { year: 2014, w: "Real Madrid" },
      { year: 2013, w: "Bayern Munich" },
      { year: 2012, w: "Chelsea" },
      { year: 2011, w: "Barcelona" },
      { year: 2010, w: "Inter Milan" },
      { year: 2009, w: "Barcelona" },
      { year: 2008, w: "Manchester United" },
      { year: 2007, w: "AC Milan" },
      { year: 2006, w: "Barcelona" },
      { year: 2005, w: "Liverpool" },
      { year: 2004, w: "FC Porto" },
      { year: 2003, w: "AC Milan" },
      { year: 2002, w: "Real Madrid" },
      { year: 2001, w: "Bayern Munich" },
      { year: 2000, w: "Real Madrid" },
      { year: 1999, w: "Manchester United" },
      { year: 1998, w: "Real Madrid" },
      { year: 1997, w: "Borussia Dortmund" },
      { year: 1996, w: "Juventus" },
      { year: 1995, w: "Ajax" },
      { year: 1994, w: "AC Milan" },
      { year: 1993, w: "Marseille" },
      { year: 1992, w: "Barcelona" },
      { year: 1991, w: "Red Star Belgrade" },
      { year: 1990, w: "AC Milan" },
      { year: 1989, w: "AC Milan" },
      { year: 1988, w: "PSV" },
      { year: 1987, w: "FC Porto" },
      { year: 1986, w: "Steaua București", logo: "FCSB" },
      { year: 1985, w: "Juventus" },
      { year: 1984, w: "Liverpool" },
      { year: 1983, w: "Hamburger SV" },
      { year: 1982, w: "Aston Villa" },
      { year: 1981, w: "Liverpool" },
      { year: 1980, w: "Nottingham Forest" },
      { year: 1979, w: "Nottingham Forest" },
      { year: 1978, w: "Liverpool" },
      { year: 1977, w: "Liverpool" },
      { year: 1976, w: "Bayern Munich" },
      { year: 1975, w: "Bayern Munich" },
      { year: 1974, w: "Bayern Munich" },
      { year: 1973, w: "Ajax" },
      { year: 1972, w: "Ajax" },
      { year: 1971, w: "Ajax" },
      { year: 1970, w: "Feyenoord" },
      { year: 1969, w: "AC Milan" },
      { year: 1968, w: "Manchester United" },
      { year: 1967, w: "Celtic" },
      { year: 1966, w: "Real Madrid" },
      { year: 1965, w: "Inter Milan" },
      { year: 1964, w: "Inter Milan" },
      { year: 1963, w: "AC Milan" },
      { year: 1962, w: "Benfica" },
      { year: 1961, w: "Benfica" },
      { year: 1960, w: "Real Madrid" },
      { year: 1959, w: "Real Madrid" },
      { year: 1958, w: "Real Madrid" },
      { year: 1957, w: "Real Madrid" },
      { year: 1956, w: "Real Madrid" }
    ]
  },
  ballondor: {
    name: "Ballon d'Or", kind: "player", noun: "awards", trophy: { img: "assets/trophies/ballon.jpg" },
    blurb: "The award for the world's best player each year (since 1956).",
    winners: [
      { year: 2025, w: "Ousmane Dembélé", cc: "FR" },
      { year: 2024, w: "Rodri", cc: "ES" },
      { year: 2023, w: "Lionel Messi", cc: "AR" },
      { year: 2022, w: "Karim Benzema", cc: "FR" },
      { year: 2021, w: "Lionel Messi", cc: "AR" },
      { year: 2019, w: "Lionel Messi", cc: "AR" },
      { year: 2018, w: "Luka Modrić", cc: "HR" },
      { year: 2017, w: "Cristiano Ronaldo", cc: "PT" },
      { year: 2016, w: "Cristiano Ronaldo", cc: "PT" },
      { year: 2015, w: "Lionel Messi", cc: "AR" },
      { year: 2014, w: "Cristiano Ronaldo", cc: "PT" },
      { year: 2013, w: "Cristiano Ronaldo", cc: "PT" },
      { year: 2012, w: "Lionel Messi", cc: "AR" },
      { year: 2011, w: "Lionel Messi", cc: "AR" },
      { year: 2010, w: "Lionel Messi", cc: "AR" },
      { year: 2009, w: "Lionel Messi", cc: "AR" },
      { year: 2008, w: "Cristiano Ronaldo", cc: "PT" },
      { year: 2007, w: "Kaká", cc: "BR" },
      { year: 2006, w: "Fabio Cannavaro", cc: "IT" },
      { year: 2005, w: "Ronaldinho", cc: "BR" },
      { year: 2004, w: "Andriy Shevchenko", cc: "UA" },
      { year: 2003, w: "Pavel Nedvěd", cc: "CZ" },
      { year: 2002, w: "Ronaldo Nazário", cc: "BR" },
      { year: 2001, w: "Michael Owen", cc: "GB-ENG" },
      { year: 2000, w: "Luís Figo", cc: "PT" },
      { year: 1999, w: "Rivaldo", cc: "BR" },
      { year: 1998, w: "Zinedine Zidane", cc: "FR" },
      { year: 1997, w: "Ronaldo Nazário", cc: "BR" },
      { year: 1996, w: "Matthias Sammer", cc: "DE" },
      { year: 1995, w: "George Weah", cc: "LR" },
      { year: 1994, w: "Hristo Stoichkov", cc: "BG" },
      { year: 1993, w: "Roberto Baggio", cc: "IT" },
      { year: 1992, w: "Marco van Basten", cc: "NL" },
      { year: 1991, w: "Jean-Pierre Papin", cc: "FR" },
      { year: 1990, w: "Lothar Matthäus", cc: "DE" },
      { year: 1989, w: "Marco van Basten", cc: "NL" },
      { year: 1988, w: "Marco van Basten", cc: "NL" },
      { year: 1987, w: "Ruud Gullit", cc: "NL" },
      { year: 1986, w: "Igor Belanov", cc: "RU" },
      { year: 1985, w: "Michel Platini", cc: "FR" },
      { year: 1984, w: "Michel Platini", cc: "FR" },
      { year: 1983, w: "Michel Platini", cc: "FR" },
      { year: 1982, w: "Paolo Rossi", cc: "IT" },
      { year: 1981, w: "Karl-Heinz Rummenigge", cc: "DE" },
      { year: 1980, w: "Karl-Heinz Rummenigge", cc: "DE" },
      { year: 1979, w: "Kevin Keegan", cc: "GB-ENG" },
      { year: 1978, w: "Kevin Keegan", cc: "GB-ENG" },
      { year: 1977, w: "Allan Simonsen", cc: "DK" },
      { year: 1976, w: "Franz Beckenbauer", cc: "DE" },
      { year: 1975, w: "Oleg Blokhin", cc: "RU" },
      { year: 1974, w: "Johan Cruyff", cc: "NL" },
      { year: 1973, w: "Johan Cruyff", cc: "NL" },
      { year: 1972, w: "Franz Beckenbauer", cc: "DE" },
      { year: 1971, w: "Johan Cruyff", cc: "NL" },
      { year: 1970, w: "Gerd Müller", cc: "DE" },
      { year: 1969, w: "Gianni Rivera", cc: "IT" },
      { year: 1968, w: "George Best", cc: "GB-NIR" },
      { year: 1967, w: "Flórián Albert", cc: "HU" },
      { year: 1966, w: "Bobby Charlton", cc: "GB-ENG" },
      { year: 1965, w: "Eusébio", cc: "PT" },
      { year: 1964, w: "Denis Law", cc: "GB-SCT" },
      { year: 1963, w: "Lev Yashin", cc: "RU" },
      { year: 1962, w: "Josef Masopust", cc: "CZ" },
      { year: 1961, w: "Omar Sívori", cc: "IT" },
      { year: 1960, w: "Luis Suárez", cc: "ES" },
      { year: 1959, w: "Alfredo Di Stéfano", cc: "ES" },
      { year: 1958, w: "Raymond Kopa", cc: "FR" },
      { year: 1957, w: "Alfredo Di Stéfano", cc: "ES" },
      { year: 1956, w: "Stanley Matthews", cc: "GB-ENG" }
    ]
  },
  euros: {
    name: "UEFA European Championship", kind: "nation", trophy: { img: "assets/trophies/euros.jpg" },
    blurb: "The championship of Europe's national teams (the 'Euros').",
    winners: [
      { year: 2024, w: "Spain", cc: "ES" },
      { year: 2020, w: "Italy", cc: "IT" },
      { year: 2016, w: "Portugal", cc: "PT" },
      { year: 2012, w: "Spain", cc: "ES" },
      { year: 2008, w: "Spain", cc: "ES" },
      { year: 2004, w: "Greece", cc: "GR" },
      { year: 2000, w: "France", cc: "FR" },
      { year: 1996, w: "Germany", cc: "DE" },
      { year: 1992, w: "Denmark", cc: "DK" },
      { year: 1988, w: "Netherlands", cc: "NL" },
      { year: 1984, w: "France", cc: "FR" },
      { year: 1980, w: "West Germany", cc: "DE" },
      { year: 1976, w: "Czechoslovakia", cc: "CZ" },
      { year: 1972, w: "West Germany", cc: "DE" },
      { year: 1968, w: "Italy", cc: "IT" },
      { year: 1964, w: "Spain", cc: "ES" },
      { year: 1960, w: "Soviet Union", cc: "RU" }
    ]
  },
  mls: {
    name: "MLS Cup", kind: "club", trophy: { icon: "🏆" },
    blurb: "The championship of Major League Soccer (USA & Canada).",
    winners: [
      { year: 2024, w: "LA Galaxy" },
      { year: 2023, w: "Columbus Crew" },
      { year: 2022, w: "LAFC" },
      { year: 2021, w: "New York City FC" },
      { year: 2020, w: "Columbus Crew" },
      { year: 2019, w: "Seattle Sounders" },
      { year: 2018, w: "Atlanta United" },
      { year: 2017, w: "Toronto FC" },
      { year: 2016, w: "Seattle Sounders" },
      { year: 2015, w: "Portland Timbers" },
      { year: 2014, w: "LA Galaxy" },
      { year: 2013, w: "Sporting Kansas City" },
      { year: 2012, w: "LA Galaxy" },
      { year: 2011, w: "LA Galaxy" },
      { year: 2010, w: "Colorado Rapids" },
      { year: 2009, w: "Real Salt Lake" },
      { year: 2008, w: "Columbus Crew" },
      { year: 2007, w: "Houston Dynamo" },
      { year: 2006, w: "Houston Dynamo" },
      { year: 2005, w: "LA Galaxy" },
      { year: 2004, w: "D.C. United" },
      { year: 2003, w: "San Jose Earthquakes" },
      { year: 2002, w: "LA Galaxy" },
      { year: 2001, w: "San Jose Earthquakes" },
      { year: 2000, w: "Kansas City Wizards" },
      { year: 1999, w: "D.C. United" },
      { year: 1998, w: "Chicago Fire" },
      { year: 1997, w: "D.C. United" },
      { year: 1996, w: "D.C. United" }
    ]
  }
};
